### ISSUE TITLE
Potentially inaccurate growth time for melons and water biomes

### ISSUE THREAD

**Issue by okx-code** [CivClassic/AnsibleSetup#130] opened 2020-12-21 01:18 UTC
I was reading the RealisticBiomes config today and I noticed some problems with the configuration of melon growth times.

As it currently stands, the growth time for different biomes is as follows:<sup>1</sup>

    biomes:
      swampy: 1.0
      hot_rainy: 0.5
      temperate: 0.25

Note here that the biomes in `swampy` are a subset of the biomes in `hot_rainy`.

When standing in a `swampy` biome, you would expect the biome multiplier to be `1.0`.
However, the biome multiplier is actually `0.5`, because it categorises the biome as `hot_rainy`. This means that the `swampy: 1.0` line is either not meant to be there or is not functioning as intended.

I also noticed that sugarcane can now grow in ocean biomes (they were only able to grow in beaches and rivers before 1.16, limiting the size of farms you could build)<sup>2</sup>, so is this a bug? This is because oceans are categorised under the water category.

I'm just asking what is intentional and what isn't. I'm happy to code a fix in RealisticBiomes myself if necessary.

[1] https://github.com/CivClassic/AnsibleSetup/blob/master/templates/public/plugins/RealisticBiomes/config.yml.j2
[2] https://docs.google.com/spreadsheets/d/1Y3sYOk533Tq9CxOcKFtnxrS4hkW_YNYxpuXyOv9_8Lo/edit#gid=0

**Comment by wingzero54** [comment] 2020-12-21 18:34
Thanks for noticing that, should be fixed [with this commit](https://github.com/CivClassic/AnsibleSetup/commit/dd35567c4127d97be338b344673997248cdf601e). I think the biomes in multiple categories was unintended and I removed the overlaps and ensured proper biome categories were listed to bring it back in-line with previous config, as you mentioned. So sugarcane shouldn't grow in ocean and melons in swamps will have the growth times as intended. If this is good I'll close the issue @okx-code

**Closed** 2020-12-21 18:49 UTC
